### ISSUE TITLE
adbyby+无法兼容最新的Adblock Plus 规则数据库

### ISSUE THREAD

**Issue by madcat0513** [coolsnowwolf/lede#10098]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
只要开启adbyby+然后自动更新到最新的Adblock Plus 规则数据库，dnsmasq就会崩溃
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：r7800 OpenWrt R22.9.1

### (3) 详细日志

A：
Tue Sep 13 08:05:35 2022 cron.err crond[30484]: crond (busybox 1.35.0) started, log level 5
Tue Sep 13 08:05:52 2022 daemon.err uhttpd[1720]: cp: can't create '/tmp/etc/dnsmasq-adbyby.d/adblock': No such file or directory
Tue Sep 13 08:05:52 2022 cron.err crond[30884]: crond (busybox 1.35.0) started, log level 5
Tue Sep 13 08:05:59 2022 daemon.err odhcp6c[2846]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Tue Sep 13 08:06:02 2022 cron.err crond[31267]: crond (busybox 1.35.0) started, log level 5
Tue Sep 13 08:06:05 2022 daemon.crit dnsmasq[31804]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Tue Sep 13 08:06:05 2022 daemon.crit dnsmasq[31804]: FAILED to start up
Tue Sep 13 08:06:10 2022 daemon.crit dnsmasq[31968]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Tue Sep 13 08:06:10 2022 daemon.crit dnsmasq[31968]: FAILED to start up
Tue Sep 13 08:06:15 2022 daemon.crit dnsmasq[31971]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Tue Sep 13 08:06:15 2022 daemon.crit dnsmasq[31971]: FAILED to start up
Tue Sep 13 08:06:20 2022 daemon.crit dnsmasq[31995]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Tue Sep 13 08:06:20 2022 daemon.crit dnsmasq[31995]: FAILED to start up
Tue Sep 13 08:06:25 2022 daemon.crit dnsmasq[32088]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Tue Sep 13 08:06:25 2022 daemon.crit dnsmasq[32088]: FAILED to start up
Tue Sep 13 08:06:30 2022 daemon.crit dnsmasq[32112]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Tue Sep 13 08:06:30 2022 daemon.crit dnsmasq[32112]: FAILED to start up
Tue Sep 13 08:06:30 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by uosX** [comment]
Wed Sep 21 00:12:22 2022 daemon.crit dnsmasq[19674]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:12:22 2022 daemon.crit dnsmasq[19674]: FAILED to start up
Wed Sep 21 00:12:22 2022 cron.err crond[19715]: crond (busybox 1.35.0) started, log level 8

x86的软路由也会这样子；
补充了以下2条订阅规则
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt

关闭Turbo ACC网络加速的，DNS缓存选项后，问题依旧；
Wed Sep 21 00:15:25 2022 daemon.crit dnsmasq[23302]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:25 2022 daemon.crit dnsmasq[23302]: FAILED to start up
Wed Sep 21 00:15:26 2022 kern.warn kernel: [168501.324993] test 65534
Wed Sep 21 00:15:27 2022 kern.warn kernel: [168502.377737] test 65534
Wed Sep 21 00:15:27 2022 kern.warn kernel: [168503.433491] test 65534
Wed Sep 21 00:15:28 2022 kern.warn kernel: [168503.753960] test 65534
Wed Sep 21 00:15:29 2022 kern.warn kernel: [168504.498719] test 65534
Wed Sep 21 00:15:29 2022 kern.warn kernel: [168505.550004] test 65534
Wed Sep 21 00:15:30 2022 kern.warn kernel: [168505.836201] test 512
Wed Sep 21 00:15:30 2022 daemon.crit dnsmasq[23325]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:30 2022 daemon.crit dnsmasq[23325]: FAILED to start up
Wed Sep 21 00:15:31 2022 kern.warn kernel: [168506.604748] test 65534
Wed Sep 21 00:15:32 2022 kern.warn kernel: [168507.658410] test 65534
Wed Sep 21 00:15:33 2022 kern.warn kernel: [168508.713028] test 65534
Wed Sep 21 00:15:34 2022 kern.warn kernel: [168509.768541] test 65534
Wed Sep 21 00:15:35 2022 daemon.crit dnsmasq[23346]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:35 2022 daemon.crit dnsmasq[23346]: FAILED to start up
Wed Sep 21 00:15:35 2022 kern.warn kernel: [168510.819120] test 65534
Wed Sep 21 00:15:36 2022 kern.warn kernel: [168511.868564] test 65534
Wed Sep 21 00:15:37 2022 kern.warn kernel: [168512.922035] test 65534
Wed Sep 21 00:15:37 2022 kern.warn kernel: [168513.818559] test 65534
Wed Sep 21 00:15:38 2022 kern.warn kernel: [168513.977830] test 65534
Wed Sep 21 00:15:39 2022 kern.warn kernel: [168515.029287] test 65534
Wed Sep 21 00:15:40 2022 daemon.crit dnsmasq[23378]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:40 2022 daemon.crit dnsmasq[23378]: FAILED to start up
Wed Sep 21 00:15:40 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Wed Sep 21 00:15:40 2022 kern.warn kernel: [168516.084328] test 65534
Wed Sep 21 00:15:41 2022 kern.warn kernel: [168517.137872] test 65534
Wed Sep 21 00:15:41 2022 kern.warn kernel: [168517.241848] test 512
Wed Sep 21 00:15:43 2022 kern.warn kernel: [168518.189266] test 65534
