### ISSUE TITLE
ksmbd: update to Git HEAD (2024-12-02),mt6000出错。x64正常。

### ISSUE THREAD

**Issue by d975xbx** [coolsnowwolf/lede#13172]
### 详细叙述

ksmbd: update to Git HEAD (2024-12-02),mt6000出错，x64正常。
ERROR: package/kernel/ksmbd failed to build

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

mt6000，x64

### 详细日志

ERROR: package/kernel/ksmbd failed to build
<img width="1596" alt="截屏2024-12-05 20 15 32" src="https://github.com/user-attachments/assets/704524a3-5593-4398-bd50-6d4ddcd4b212">

**Comment by xydche** [comment]
玩客云也报错了

**Comment by liwenjie119** [comment]
ksmd.tools也有报错：
lto1: fatal error: bytecode stream in file '/home/ubuntu/lede/staging_dir/target-x86_64_musl/usr/lib/libglib-2.0.a' generated with LTO version 11.3 instead of the expected 13.1
compilation terminated.
lto-wrapper: fatal error: x86_64-openwrt-linux-musl-gcc returned 1 exit status
compilation terminated.
/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-13.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/13.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld.bfd: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:116: /home/ubuntu/lede/build_dir/target-x86_64_musl/ksmbd-tools-3.4.7/.built] Error 1

**Comment by coolsnowwolf** [comment]
修复了
