### ISSUE TITLE
能否加入airconnect模块

### ISSUE THREAD

**Issue by ragelancer** [coolsnowwolf/lede#5699]
你好，L大。
airconnect是一个将音频通过airplay串流到不支持airplay的dlna/upnp设备上的软件。
详细介绍见 https://github.com/philippe44/AirConnect
请问能否将其功能整合进openwrt里呢。

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/96960491-1d107580-1535-11eb-88b8-e1c39c6d7b93.png)

**Comment by ragelancer** [comment]
多谢L大，那请问在编译的时候选择哪个组件，没有找到类似luci-app-airconnect这样名称的组件。

**Comment by sxx1314** [comment]
这个项目多贴心，直接预编译好了。  直接下载二进制写好config运行即可。另外docker也有现成镜像。

**Comment by ragelancer** [comment]
> 这个项目多贴心，直接预编译好了。 直接下载二进制写好config运行即可。另外docker也有现成镜像。

我把预编译好的文件放在了/bin目录下，也设置了运行权限
但运行后提示
`-ash: ./airupnp-aarch64: not found
`请问这是怎么回事？

**Comment by erdrd** [comment]
@coolsnowwolf 
Since you seem to have had some success with AirConnect on OpenWrt and a similar setup, I assume, I have two questions:

1. On my router (Espressobin, Marvell Armada 88F3700 based), I can run the airupnp-aarch64-static binary fine, but do not discover any devices. looks like multicast interference on the router itself (since the the rest of the network has no issues; I can run a docker container on unraid with airconnect just fine, but would prefer to have it run on the router). 
Any settings/configs that are non-obvious?

2. where can I find your luci-app-airconnect? :)

Thanks
A
