### ISSUE TITLE
SSR plus服务器连接OK但是不能fq

### ISSUE THREAD

**Issue by LoogCP** [coolsnowwolf/lede#681]
在状态里面谷歌连通性检查显示连接错误,服务器端口检查显示OK,不能翻墙
ssh用/etc/init.d/shadowsocksr restart输出
```
root@OpenWrt:~# /etc/init.d/shadowsocksr restart  
udhcpc: started, v1.29.2  
udhcpc: sending discover
udhcpc: no lease, failing
sh: 1: unknown operand
ipset v6.38: Element cannot be added to the set: it's already added
ipset v6.38: Element cannot be added to the set: it's already added
ipset v6.38: Element cannot be added to the set: it's already added
ipset v6.38: Element cannot be added to the set: it's already added
ipset v6.38: Element cannot be added to the set: it's already added
sh: 1: unknown operand
sh: 1: unknown operand
 2018-10-16 12:53:36 INFO: protocol auth_chain_b
 2018-10-16 12:53:36 INFO: protocol_param 
 2018-10-16 12:53:36 INFO: method aes-256-ctr
 2018-10-16 12:53:36 INFO: obfs tls1.2_ticket_auth
 2018-10-16 12:53:36 INFO: obfs_param 
udhcpc: started, v1.29.2
udhcpc: sending discover
udhcpc: no lease, failing
root@OpenWrt:~# 
```

服务器是OK的,手机上能连能用,固件版本是OpenWrt 18.06.1, r827-5f9650a5,R8.1.7

**Comment by coolsnowwolf** [comment]
重启即可，估计你是升级过来的，把老版本配置带过了

**Comment by LoogCP** [comment]
> 重启即可，估计你是升级过来的，把老版本配置带过了

我升级的时候是选择了不保留配置,后面所有配置都是自己改的,中间重启过,还是不行

**Comment by LoogCP** [comment]
> 重启即可，估计你是升级过来的，把老版本配置带过了

老版本的配置我只把DHCP和network的用SCP传到路由器里边,其他配置都没用老版本的

**Comment by nimasi** [comment]
订阅功能可以正常使用吗

**Comment by LoogCP** [comment]
> 订阅功能可以正常使用吗

订阅能用，但是订阅服务列表里面的服务器部分OK，部分error，但是不管选哪个服务器，都过不了连通性测试，访问不了Google之类的网站

**Comment by chinawenxu** [comment]
一样的问题。服务器是好的，但不能翻墙。

**Comment by self7414386** [comment]
ros 加openwrt ，ssr plus显示运行，状态中显示可以连接谷歌，却不能连接是什么原因？

**Comment by self7414386** [comment]
ros 加openwrt ，ssr plus显示运行，状态中显示可以连接谷歌，却不能连接是什么原因？

**Comment by dpwfor** [comment]
一样的问题，服务器正常，手机测试可以，路由器设置，连通性失败，怎么回事

**Comment by coofly** [comment]
我也遇到了这样的问题，这是什么情况？

**Comment by dpwfor** [comment]
节点的问题，换了节点解决的


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 方文雄 <notifications@github.com&gt;
发送时间: 2020年3月24日 00:08
收件人: coolsnowwolf/lede <lede@noreply.github.com&gt;
抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681)





 
我也遇到了这样的问题，这是什么情况？

**Comment by wo673060519** [comment]
解决了吗，咋解决的

**Comment by dpwfor** [comment]
节点问题，换了我的节点可以了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wo673060519 <notifications@github.com&gt;
发送时间: 2020年4月1日 15:41
收件人: coolsnowwolf/lede <lede@noreply.github.com&gt;
抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681)





 
解决了吗，咋解决的

**Comment by wo673060519** [comment]
> 节点问题，换了我的节点可以了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wo673060519 <notifications@github.com&gt; 发送时间: 2020年4月1日 15:41 收件人: coolsnowwolf/lede <lede@noreply.github.com&gt; 抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681) 解决了吗，咋解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我的是VPS啊，没法换啊。应该不是节点的问题吧

**Comment by dpwfor** [comment]
我的是换节点解决的，你不行可以用我机场的节点测试


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wo673060519 <notifications@github.com&gt;
发送时间: 2020年4月1日 16:15
收件人: coolsnowwolf/lede <lede@noreply.github.com&gt;
抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681)





  
节点问题，换了我的节点可以了 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: wo673060519 <notifications@github.com&gt; 发送时间: 2020年4月1日 15:41 收件人: coolsnowwolf/lede <lede@noreply.github.com&gt; 抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681) 解决了吗，咋解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我的是VPS啊，没法换啊。应该不是节点的问题吧

**Comment by wo673060519** [comment]
> 节点问题，换了我的节点可以了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wo673060519 <notifications@github.com&gt; 发送时间: 2020年4月1日 15:41 收件人: coolsnowwolf/lede <lede@noreply.github.com&gt; 抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681) 解决了吗，咋解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

而且我的昨天还能正常用的，今天没啥征兆就不行了，但是手机连接可以用，公司电脑也能用，我怀疑应该是openwrt的问题。

**Comment by dpwfor** [comment]
那可能就是固件的问题，建议换版本


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wo673060519 <notifications@github.com&gt;
发送时间: 2020年4月1日 16:17
收件人: coolsnowwolf/lede <lede@noreply.github.com&gt;
抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681)





  
节点问题，换了我的节点可以了 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: wo673060519 <notifications@github.com&gt; 发送时间: 2020年4月1日 15:41 收件人: coolsnowwolf/lede <lede@noreply.github.com&gt; 抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681) 解决了吗，咋解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
而且我的昨天还能正常用的，今天没啥征兆就不行了，但是手机连接可以用，公司电脑也能用，我怀疑应该是openwrt的问题。

**Comment by wo673060519** [comment]
> 那可能就是固件的问题，建议换版本 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wo673060519 <notifications@github.com&gt; 发送时间: 2020年4月1日 16:17 收件人: coolsnowwolf/lede <lede@noreply.github.com&gt; 抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681) 节点问题，换了我的节点可以了 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: wo673060519 <notifications@github.com&gt; 发送时间: 2020年4月1日 15:41 收件人: coolsnowwolf/lede <lede@noreply.github.com&gt; 抄送: dpwfor <1130277684@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[coolsnowwolf/lede] SSR plus服务器连接OK但是不能fq (#681) 解决了吗，咋解决的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 而且我的昨天还能正常用的，今天没啥征兆就不行了，但是手机连接可以用，公司电脑也能用，我怀疑应该是openwrt的问题。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，多谢兄弟解答。

**Comment by SundarZhou** [comment]
有大佬解决这个问题解决了吗，我也是加了正常能使用的服务器，但是测试连接失败

**Comment by simpleyang1** [comment]
同样的问题，订阅也可以正常更新，测试也是好的，但是就是不能翻墙，不知道哪里问题，新刷了系统进r2s然后更新的订阅。固件是这个

klever1988/nanopi-openwrt 2022-05-26
--


[klever1988/nanopi-openwrt](https://github.com/klever1988/nanopi-openwrt) 2022-05-26

**Comment by tesssar** [comment]
> 同样的问题，订阅也可以正常更新，测试也是好的，但是就是不能翻墙，不知道哪里问题，新刷了系统进r2s然后更新的订阅。固件是这个
> 
> ## klever1988/nanopi-openwrt 2022-05-26
> [klever1988/nanopi-openwrt](https://github.com/klever1988/nanopi-openwrt) 2022-05-26

哈哈，我也是同样的问题，Google了一下跳转进来发现你用的也是1988的固件。我刷了两个版本的固件了都有同样的问题，节点是没问题的，因为同样的节点改用vssr就没问题了。

**Comment by hunter8605** [comment]
我也是同样的问题，头大头大

**Comment by tesssar** [comment]
用了几个月vssr感觉也不错，跟ssrp差不多

**Comment by tesssar** [comment]
> 我也是同样的问题，头大头大


用了几个月vssr感觉也不错，跟ssrp差不多

**Comment by hunter8605** [comment]
请问支持hy协议吗？

tesssar ***@***.***> 于2022年9月10日周六 19:39写道：

**Comment by RaphaelDante** [comment]
我也遇到这个问题了，跟你一样的情况，而且还另外试了passwall和clash，都不行，之前用passwall一直没问题的，请问怎么解决的

**Comment by zeroworld1** [comment]
一样的问题，trojan协议，ssr plus可以连上服务器，并且端口也都测试ok（百度和google），但是无法翻墙。
用passwall和openclash也是一样无法翻墙。怀疑是墙高了的原因。

**Comment by Jogmann** [comment]
清除一下DNS缓存：调出CMD，  ipconfig/flushDNS

**Comment by qian-cr** [comment]
> 一样的问题，trojan协议，ssr plus可以连上服务器，并且端口也都测试ok（百度和google），但是无法翻墙。 用passwall和openclash也是一样无法翻墙。怀疑是墙高了的原因。

解决了吗？我也一样，可以运行，百度和Google测试也OK，但就是翻不出去

**Comment by qian-cr** [comment]
我也是这样，但是发现其他外网都能连，唯独Google、YouTube连不上

**Comment by qian-cr** [comment]
难道墙又高了？除了Google、主流媒体不能访问，其他外网可以

**Comment by ZerOri** [comment]
已经放弃路由器插件翻墙了
